/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package runmylibrary;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author TOSHIBA
 */
public class RunMyLibrary {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new WELCOME_KCCF().setVisible(true);
            }
        });
            
    }
    
}


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 *
 * @author TOSHIBA
 */

class AposthropheException extends Exception{
    
    public AposthropheException(String message){
        super(message);
    }
    
}



class Books {
    private int accnum;
    private String datereceived;
    private String classificationnum;
    private String author;
    private String title;
    private String edition;
    private String volume;
    private String numofpages;
    private String sourceoffunds;
    private String costprice;
    private String placepublication;
    private String publisher;
    private String copyrightyear;
    private String remarks;    
    
    
    public Books(int accnum1 , String datereceived1, String classificationnum1, String author1, String title1, String edition1, String volume1, String numofpages1, String sourceoffunds1,String costprice1, String placepublication1,String publisher1,String copyrightyear1,String remarks1)
    {
        this.accnum = accnum1;
        this.datereceived = datereceived1;
        this.classificationnum = classificationnum1;
        this.author=author1;
        this.title=title1;
        this.edition=edition1;
        this.volume=volume1;
        this.numofpages=numofpages1;
        this.sourceoffunds=sourceoffunds1;
        this.costprice=costprice1;
        this.placepublication=placepublication1;
        this.publisher=publisher1;
        this.copyrightyear=copyrightyear1;
        this.remarks=remarks1;
        
     
    }
    
    public int getaccNum()
    {
        return accnum;
    }
    
    public String getDateReceived()
    {
        return datereceived;
    }
    
    public String getClassificationNum()
    {
        return classificationnum;
    }
    public String getAuthor()
    {
        return author;
    }
    
    public String getTitle()
    {
        return title;
    }
    
     public String getEdition()
    {
        return edition;
    }
    
    public String getVolume()
    {
        return volume;
    }
    public String getNumOfPages()
    {
        return numofpages;
    }
    
    public String getSourceOfFunds()
    {
        return sourceoffunds;
    }
    
    public String getCostPrice()
    {
        return costprice;
    }
    
    public String getPlacePublication()
    {
        return placepublication;
    }
    
    
    public String getPublisher()
    {
        return publisher;
    }
    
    public String getCopyrightYear()
    {
        return copyrightyear;
    }
    public String getRemarks()
    {
        return remarks;
    }
}


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author TOSHIBA
 */
class Library_management_system extends javax.swing.JFrame {

    /**
     * Creates new form Library_management_system
     */
    public Library_management_system() {
       
        initComponents();
        
        Show_Books_In_JTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        authorTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        accnumTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        titleTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        classnumTF = new javax.swing.JTextField();
        daterecieveTF = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        editionTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        volumeTF = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        numpagesTF = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        sourcefundTF = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        costpriceTF = new javax.swing.JTextField();
        placepublicationTF = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        publisherTF = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        copyrightTF = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        remarksTF = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        deletebutton = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        addbutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        deletebutton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIBRARY MANAGEMENT SYSTEM");
        setBackground(new java.awt.Color(212, 212, 212));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1375, 775));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(1375, 711));
        jPanel1.setPreferredSize(new java.awt.Dimension(1380, 730));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(212, 212, 212));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(51, 204, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("LIBRARY MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(469, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(457, 457, 457))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 1340, 70);

        jPanel3.setBackground(new java.awt.Color(212, 212, 212));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(212, 212, 212));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 5));
        jPanel6.setLayout(null);

        authorTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        authorTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        authorTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorTFActionPerformed(evt);
            }
        });
        jPanel6.add(authorTF);
        authorTF.setBounds(290, 90, 240, 21);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Author:");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(230, 80, 90, 36);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Title: ");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(10, 116, 91, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Date Recieved:");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(230, 40, 107, 36);

        accnumTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        accnumTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.add(accnumTF);
        accnumTF.setBounds(110, 50, 55, 21);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Classification No.:");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(20, 80, 120, 36);

        titleTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.add(titleTF);
        titleTF.setBounds(100, 120, 309, 21);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Books for:");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(10, 10, 91, 36);

        classnumTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        classnumTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.add(classnumTF);
        classnumTF.setBounds(140, 90, 55, 20);

        daterecieveTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        daterecieveTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.add(daterecieveTF);
        daterecieveTF.setBounds(340, 50, 180, 21);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ELEMENTARY", "HIGH SCHOOL", "COLLEGE" }));
        jPanel6.add(jComboBox1);
        jComboBox1.setBounds(90, 10, 170, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Accession No.:");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(10, 40, 91, 36);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Edition:");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(10, 150, 71, 36);

        editionTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editionTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.add(editionTF);
        editionTF.setBounds(90, 160, 124, 21);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Volume:");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(260, 150, 66, 36);

        volumeTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        volumeTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.add(volumeTF);
        volumeTF.setBounds(330, 160, 190, 21);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("No. of Pages:");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(10, 190, 91, 36);

        numpagesTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        numpagesTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        numpagesTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpagesTFActionPerformed(evt);
            }
        });
        jPanel6.add(numpagesTF);
        numpagesTF.setBounds(110, 200, 55, 21);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Source of Funds:");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(230, 190, 107, 36);

        sourcefundTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sourcefundTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sourcefundTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourcefundTFActionPerformed(evt);
            }
        });
        jPanel6.add(sourcefundTF);
        sourcefundTF.setBounds(340, 200, 180, 21);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(10, 10, 550, 300);

        jPanel7.setBackground(new java.awt.Color(212, 212, 212));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 5));
        jPanel7.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Cost Price:");
        jPanel7.add(jLabel23);
        jLabel23.setBounds(10, 10, 91, 36);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Place of Publication:");
        jPanel7.add(jLabel24);
        jLabel24.setBounds(210, 10, 139, 36);

        costpriceTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        costpriceTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.add(costpriceTF);
        costpriceTF.setBounds(110, 20, 55, 21);

        placepublicationTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        placepublicationTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.add(placepublicationTF);
        placepublicationTF.setBounds(340, 20, 180, 21);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Publisher:");
        jPanel7.add(jLabel26);
        jLabel26.setBounds(10, 40, 91, 36);

        publisherTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        publisherTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        publisherTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherTFActionPerformed(evt);
            }
        });
        jPanel7.add(publisherTF);
        publisherTF.setBounds(100, 50, 370, 21);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Copyright Year:");
        jPanel7.add(jLabel28);
        jLabel28.setBounds(10, 80, 110, 36);

        copyrightTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        copyrightTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.add(copyrightTF);
        copyrightTF.setBounds(120, 90, 170, 21);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Remarks:");
        jPanel7.add(jLabel29);
        jLabel29.setBounds(10, 120, 91, 36);

        remarksTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        remarksTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        remarksTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remarksTFActionPerformed(evt);
            }
        });
        jPanel7.add(remarksTF);
        remarksTF.setBounds(100, 130, 370, 21);

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setText("Clear TextFields");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 5));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton9);
        jButton9.setBounds(390, 190, 120, 30);

        jPanel3.add(jPanel7);
        jPanel7.setBounds(570, 9, 570, 300);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 90, 1150, 320);

        jPanel4.setBackground(new java.awt.Color(212, 212, 212));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        deletebutton.setBackground(new java.awt.Color(204, 204, 204));
        deletebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletebutton.setText("Delete");
        deletebutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 5));
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel4.add(deletebutton);
        deletebutton.setBounds(10, 210, 160, 44);

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Refresh Table");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 5));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);
        jButton8.setBounds(10, 160, 160, 44);

        addbutton.setBackground(new java.awt.Color(204, 204, 204));
        addbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addbutton.setText("Add Books");
        addbutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 5));
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        jPanel4.add(addbutton);
        addbutton.setBounds(10, 10, 160, 44);

        updatebutton.setBackground(new java.awt.Color(204, 204, 204));
        updatebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatebutton.setText("Update");
        updatebutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 5));
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        jPanel4.add(updatebutton);
        updatebutton.setBounds(10, 110, 160, 44);

        searchButton.setBackground(new java.awt.Color(204, 204, 204));
        searchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchButton.setText("Search");
        searchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 5));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel4.add(searchButton);
        searchButton.setBounds(10, 60, 160, 44);

        deletebutton1.setBackground(new java.awt.Color(204, 204, 204));
        deletebutton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletebutton1.setText("Exit");
        deletebutton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 5));
        deletebutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebutton1ActionPerformed(evt);
            }
        });
        jPanel4.add(deletebutton1);
        deletebutton1.setBounds(10, 260, 160, 44);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(1170, 90, 180, 320);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTable1.setBackground(new java.awt.Color(212, 212, 212));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Accession No.", "Date Recieved", "Classification No.", "Author", "Title", "Edition", "Volume", "No.Pages", "Source of Funds", "Cost Price", "Place of Publication", "Publisher", "Copyright Year", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setIntercellSpacing(new java.awt.Dimension(1, 1));
        jTable1.setSelectionBackground(new java.awt.Color(0, 204, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
            jTable1.getColumnModel().getColumn(10).setResizable(false);
            jTable1.getColumnModel().getColumn(11).setResizable(false);
            jTable1.getColumnModel().getColumn(12).setResizable(false);
            jTable1.getColumnModel().getColumn(13).setResizable(false);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 420, 1330, 310);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1400, 780);

        pack();
    }// </editor-fold>                        

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        try { 
           
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/kccf_db_library","root",""); 
            Statement st = conn.createStatement(); 
            String accnum =accnumTF.getText();
            String daterecieve=daterecieveTF.getText();
            String classnum=classnumTF.getText();
            String author =authorTF.getText();
            String title=titleTF.getText();
            String edition=editionTF.getText();
            String volume =volumeTF.getText();
            String numpages=numpagesTF.getText();
            String sourcefund=sourcefundTF.getText();
            String costprice=costpriceTF.getText();
            String placepublication=placepublicationTF.getText();
            String publisher =publisherTF.getText();
            String copyright=copyrightTF.getText();
            String remarks=remarksTF.getText();
            
            int num = Integer.parseInt(accnum);
            
            try{
                 Scanning_Aposthrophe(accnum);
                 Scanning_Aposthrophe(daterecieve);
                 Scanning_Aposthrophe(classnum);
                 Scanning_Aposthrophe(author);
                 Scanning_Aposthrophe(title);
                 Scanning_Aposthrophe(edition);
                 Scanning_Aposthrophe(volume);
                 Scanning_Aposthrophe(numpages);
                 Scanning_Aposthrophe(costprice);
                 Scanning_Aposthrophe(placepublication);
                 Scanning_Aposthrophe(copyright);
                 Scanning_Aposthrophe(publisher);
                 Scanning_Aposthrophe(copyright);
                 Scanning_Aposthrophe(remarks);
                 
            }catch(AposthropheException e){
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
            String compareString="Select * FROM books_table WHERE Accession_No='"+num+"'";
            ResultSet result=st.executeQuery(compareString);
            
            if(result.next()){
                //JOptionPane.showMessageDialog(rootPane,"ALERT:\nAccession Number is Already exist.");
                int isExist = JOptionPane.showConfirmDialog(rootPane,"ALERT:\nAccession Number is Already exist.\nDo you wan to replace it?","Accession Exist",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if(isExist ==JOptionPane.YES_OPTION){
                
                    String query="UPDATE `books_table` SET `Accession_No`='"+num+"',`Date_Recieved`='"+daterecieve+"',`Classification_No.`='"+classnum+"',`Author`='"+author+"',`Title`='"+title+"',`Edition`='"+edition+"',`Volume`='"+volume+"',`No._of_Pages`='"+numpages+"',`Source_of_Funds`='"+sourcefund+"',`Cost_Price`='"+costprice+"',`Place_of_Publication`='"+placepublication+"',`Publisher`='"+publisher+"',`Copyright_year`='"+copyright+"',`Remarks`='"+remarks+"' WHERE Accession_No='"+num+"'";
        
                    getConnection().createStatement().execute(query);

                    refreshTable();
                    Maintain_Column_Size();
                    Clear_TextFields();

            }
            }else{
                int addbookyesno = JOptionPane.showConfirmDialog(rootPane,"Do you want to add Accession Number "+accnum+" to your book List?","Addbooks?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                 if(addbookyesno ==JOptionPane.YES_OPTION){
            st.executeUpdate("INSERT INTO books_table " + 
                "VALUES ('"+num+"', '"+daterecieve+"','"+classnum+"', '"+author+"','"+title+"', '"+edition+"','"+volume+"', '"+numpages+"','"+sourcefund+"','"+costprice+"', '"+placepublication+"','"+publisher+"', '"+copyright+"','"+remarks+"')"); 
            
            
            JOptionPane.showMessageDialog(null,""+accnumTF.getText()+" Added!"); 
            Clear_TextFields();
            
            refreshTable();
            Maintain_Column_Size();
            
            }
            }
            
            conn.close(); 
        } catch (Exception e) { 
            System.err.println("Got an exception! "); 
            System.err.println(e.getMessage()); 
        }
        
    }                                         

    
    
    private void authorTFActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void numpagesTFActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void sourcefundTFActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void publisherTFActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void remarksTFActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(rootPane,"Sure? You want to delete Accession Number "+accnumTF.getText()+"?","Delete",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        int row=jTable1.getSelectedRow();
       String cell = jTable1.getModel().getValueAt(row, 0).toString();
       String sql="DELETE FROM books_table where Accession_No ="+cell;
        try{
            if(result ==JOptionPane.YES_OPTION){
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/kccf_db_library","root",""); 
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null,""+accnumTF.getText()+" Deleted!"); 

                refreshTable();
                Maintain_Column_Size();
                Clear_TextFields();
                

            }else{
                System.out.println("Deletion Aborted");
            }
            
        } catch(Exception e){
            e.printStackTrace();
        }
    }                                            

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        
        accnumTF.setText(model.getValueAt(i,0).toString());
            daterecieveTF.setText(model.getValueAt(i,1).toString());
            classnumTF.setText(model.getValueAt(i,2).toString());
            authorTF.setText(model.getValueAt(i,3).toString());
            titleTF.setText(model.getValueAt(i,4).toString());
            editionTF.setText(model.getValueAt(i,5).toString());
            volumeTF.setText(model.getValueAt(i,6).toString());
            numpagesTF.setText(model.getValueAt(i,7).toString());
            sourcefundTF.setText(model.getValueAt(i,8).toString());
            costpriceTF.setText(model.getValueAt(i,9).toString());
            placepublicationTF.setText(model.getValueAt(i,10).toString());
            publisherTF.setText(model.getValueAt(i,11).toString());
            copyrightTF.setText(model.getValueAt(i,12).toString());
            remarksTF.setText(model.getValueAt(i,13).toString());
            
    }                                    

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
          int resultSEARCH = JOptionPane.showConfirmDialog(rootPane,"Sure? You want to Update Accession Number "+accnumTF.getText()+"?","Update?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
          if(resultSEARCH ==JOptionPane.YES_OPTION){   
        try {
            String accnum =accnumTF.getText();
            String daterecieve=daterecieveTF.getText();
            String classnum=classnumTF.getText();
            String author =authorTF.getText();
            String title=titleTF.getText();
            String edition=editionTF.getText();
            String volume =volumeTF.getText();
            String numpages=numpagesTF.getText();
            String sourcefund=sourcefundTF.getText();
            String costprice=costpriceTF.getText();
            String placepublication=placepublicationTF.getText();
            String publisher =publisherTF.getText();
            String copyright=copyrightTF.getText();
            String remarks=remarksTF.getText();
            
            int num = Integer.parseInt(accnum);
            
             
            try{
              
                 Scanning_Aposthrophe(accnum);
                 Scanning_Aposthrophe(daterecieve);
                 Scanning_Aposthrophe(classnum);
                 Scanning_Aposthrophe(author);
                 Scanning_Aposthrophe(title);
                 Scanning_Aposthrophe(edition);
                 Scanning_Aposthrophe(volume);
                 Scanning_Aposthrophe(numpages);
                 Scanning_Aposthrophe(costprice);
                 Scanning_Aposthrophe(placepublication);
                 Scanning_Aposthrophe(copyright);
                 Scanning_Aposthrophe(publisher);
                 Scanning_Aposthrophe(copyright);
                 Scanning_Aposthrophe(remarks);
                 
            }catch(AposthropheException e){
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        String query="UPDATE `books_table` SET `Accession_No`='"+num+"',`Date_Recieved`='"+daterecieve+"',`Classification_No.`='"+classnum+"',`Author`='"+author+"',`Title`='"+title+"',`Edition`='"+edition+"',`Volume`='"+volume+"',`No._of_Pages`='"+numpages+"',`Source_of_Funds`='"+sourcefund+"',`Cost_Price`='"+costprice+"',`Place_of_Publication`='"+placepublication+"',`Publisher`='"+publisher+"',`Copyright_year`='"+copyright+"',`Remarks`='"+remarks+"' WHERE Accession_No='"+num+"'";
        
        getConnection().createStatement().execute(query);
        
        JOptionPane.showMessageDialog(null,""+accnumTF.getText()+" Updated!");  
        refreshTable();
        Maintain_Column_Size();
        Clear_TextFields();
        
        } catch (SQLException ex ) {
            Logger.getLogger(Library_management_system.class.getName()).log(Level.SEVERE, null, ex);
            
        
        }
        
          }
        
    }                                            

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Clear_TextFields();
    }                                        

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        Search_Data();
    }                                            

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        refreshTable();
        Maintain_Column_Size();
    }                                        

    private void deletebutton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        System.exit(0);
    }                                             

    
     public Connection getConnection(){
       Connection con;
       try {
           Class.forName("com.mysql.jdbc.Driver");
           
           con = DriverManager.getConnection("jdbc:mysql://localhost/kccf_db_library", "root","");
             System.out.println("connected");
             
           return con;
           
       } catch (Exception e) {
           e.printStackTrace();
           JOptionPane.showMessageDialog(null, "ERROR:\nDatabase not connected.\nPlease start XAMPP.");
           return null;
       }
   }
     
     public void Clear_TextFields(){
            accnumTF.setText("");
            daterecieveTF.setText("");
            classnumTF.setText("");
            authorTF.setText("");
            titleTF.setText("");
            editionTF.setText("");
            volumeTF.setText("");
            numpagesTF.setText("");
            sourcefundTF.setText("");
            costpriceTF.setText("");
            placepublicationTF.setText("");
            publisherTF.setText("");
            copyrightTF.setText("");
            remarksTF.setText("");
            
     }
    
     public ArrayList<Books> getBooksList(){
       ArrayList<Books> booksList = new ArrayList<>();
       Connection connection = getConnection();
       
       String query= "SELECT * FROM `books_table` ORDER BY `books_table`.`Accession_No` ASC";
       Statement st;
       ResultSet rs;
       
       try {
           st = connection.createStatement();
           rs = st.executeQuery(query);
           Books books;
           while(rs.next())
           {
               books = new Books(rs.getInt("Accession_No"),rs.getString("Date_Recieved"),rs.getString("Classification_No."),rs.getString("Author"),rs.getString("Title"),rs.getString("Edition"),rs.getString("Volume"),rs.getString("No._of_Pages"),rs.getString("Source_of_Funds"),rs.getString("Cost_Price"),rs.getString("Place_of_Publication"),rs.getString("Publisher"),rs.getString("Copyright_year"),rs.getString("Remarks"));
               booksList.add(books);
           }
       } catch (SQLException e) {
       }
       return booksList;
   }
     
     public void Search_Data(){
     
        // String query="SELECT * FROM `books_table` WHERE `Accession_No`='"+accnumTF.getText()+"'";
         try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/kccf_db_library","root",""); 
           
            
            String daterecieve=daterecieveTF.getText();
            String classnum=classnumTF.getText();
            String author =authorTF.getText();
            String title=titleTF.getText();
            String edition=editionTF.getText();
            String volume =volumeTF.getText();
            String numpages=numpagesTF.getText();
            String sourcefund=sourcefundTF.getText();
            String costprice=costpriceTF.getText();
            String placepublication=placepublicationTF.getText();
            String publisher =publisherTF.getText();
            String copyright=copyrightTF.getText();
            String remarks=remarksTF.getText();
  
            String query=null;
            if(!accnumTF.getText().isEmpty())
                query="SELECT * FROM `books_table` WHERE `Accession_No` LIKE '"+accnumTF.getText()+"'";
            
            else if(!daterecieve.isEmpty())
                query="SELECT * FROM `books_table` WHERE `Date_Recieved` LIKE '"+daterecieve+"'";
            
            else if(!classnum.isEmpty())
                query="SELECT * FROM `books_table` WHERE `Classification_No.` LIKE '"+classnum+"'";
            
            else if(!author.isEmpty())
                query="SELECT * FROM `books_table` WHERE `Author` LIKE '"+author+"'";
            
            else if(!title.isEmpty())
                query="SELECT * FROM `books_table` WHERE `Title` LIKE '"+title+"%"+"'";
            
            else if(!edition.isEmpty())
                query="SELECT * FROM `books_table` WHERE `Edition` LIKE '"+edition+"'";
            
            else if(!volume.isEmpty())
                query="SELECT * FROM `books_table` WHERE `Volume` LIKE '"+volume+"'";
            
            else if(!numpages.isEmpty())
                query="SELECT * FROM `books_table` WHERE `No._of_Pages` LIKE '"+numpages+"'";
            
            else if(!sourcefund.isEmpty())
                query="SELECT * FROM `books_table` WHERE `Source_of_Funds` LIKE '"+sourcefund+"'";
            
            else if(!costprice.isEmpty())
                query="SELECT * FROM `books_table` WHERE `Cost_Price` LIKE '"+costprice+"'";
            
            else if(!placepublication.isEmpty())
                query="SELECT * FROM `books_table` WHERE `Place_of_Publication` LIKE '"+placepublication+"'";
            
            else if(!publisher.isEmpty())
                query="SELECT * FROM `books_table` WHERE `Publisher` LIKE '"+publisher+"%"+"'";
            
            else if(!copyright.isEmpty())
                query="SELECT * FROM `books_table` WHERE `Copyright_year` LIKE '"+copyright+"'";
            
            else if(!remarks.isEmpty())
                query="SELECT * FROM `books_table` WHERE `Remarks` LIKE '"+remarks+"%"+"'";
            

            else
                query="SELECT * FROM `books_table`";
            
            
            
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            Maintain_Column_Size();
            Clear_TextFields();
            pst.close();
            rs.close();
        } catch(Exception e){
            e.printStackTrace();
        }
     }
     
     public void refreshTable(){
         
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/kccf_db_library","root",""); 
       
            String query1= "SELECT * FROM `books_table` ORDER BY `books_table`.`Accession_No` ASC";
            PreparedStatement pst1 = conn.prepareStatement(query1);
            ResultSet rs1=pst1.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
           
        
            pst1.close();
            rs1.close();
        } catch(Exception e){
            e.printStackTrace();
        }
    }
     
    public void Maintain_Column_Size(){
       jTable1.getColumnModel().getColumn(0).setPreferredWidth(93);
       jTable1.getColumnModel().getColumn(1).setPreferredWidth(93);
       jTable1.getColumnModel().getColumn(2).setPreferredWidth(98);
       jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
       jTable1.getColumnModel().getColumn(4).setPreferredWidth(200);
       jTable1.getColumnModel().getColumn(5).setPreferredWidth(70);
       jTable1.getColumnModel().getColumn(6).setPreferredWidth(60);
       jTable1.getColumnModel().getColumn(7).setPreferredWidth(70);
       jTable1.getColumnModel().getColumn(8).setPreferredWidth(100);
       jTable1.getColumnModel().getColumn(10).setPreferredWidth(90);
       jTable1.getColumnModel().getColumn(11).setPreferredWidth(100);
       jTable1.getColumnModel().getColumn(12).setPreferredWidth(60);
       jTable1.getColumnModel().getColumn(13).setPreferredWidth(80);
     
    }
    
    public void Show_Books_In_JTable(){
       ArrayList<Books> list = getBooksList();
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       Object[] row = new Object[15];
       Maintain_Column_Size();
       for(int i = 0; i < list.size(); i++)
       {
           row[0] = list.get(i).getaccNum();
           row[1] = list.get(i).getDateReceived();
           row[2] = list.get(i).getClassificationNum();
           row[3] = list.get(i).getAuthor();
           row[4] = list.get(i).getTitle();
           row[5] = list.get(i).getEdition();
           row[6] = list.get(i).getVolume();
           row[7] = list.get(i).getNumOfPages();
           row[8] = list.get(i).getSourceOfFunds();
           row[9] = list.get(i).getCostPrice();
           row[10] = list.get(i).getPlacePublication();
           row[11] = list.get(i).getPublisher();
           row[12] = list.get(i).getCopyrightYear();
           row[13] = list.get(i).getRemarks();
           
         
         
           
           model.addRow(row);
       }
    }
   
   public void Scanning_Aposthrophe(String word)throws AposthropheException{
       if (word.contains("'")||word.contains("\"")){
           throw new AposthropheException("Check all textfields:\nRemove single Quote(') or a Double Qoute(\")!");
       }
   }
    
    
   

    // Variables declaration - do not modify                     
    private javax.swing.JTextField accnumTF;
    private javax.swing.JButton addbutton;
    private javax.swing.JTextField authorTF;
    private javax.swing.JTextField classnumTF;
    private javax.swing.JTextField copyrightTF;
    private javax.swing.JTextField costpriceTF;
    private javax.swing.JTextField daterecieveTF;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton deletebutton1;
    private javax.swing.JTextField editionTF;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField numpagesTF;
    private javax.swing.JTextField placepublicationTF;
    private javax.swing.JTextField publisherTF;
    private javax.swing.JTextField remarksTF;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField sourcefundTF;
    private javax.swing.JTextField titleTF;
    private javax.swing.JButton updatebutton;
    private javax.swing.JTextField volumeTF;
    // End of variables declaration                   
}



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author TOSHIBA
 */
class WELCOME_KCCF extends javax.swing.JFrame {

    /**
     * Creates new form WELCOME_KCCF
     */
    public WELCOME_KCCF() {
        initComponents();
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                int i;
            for(i=0; i<101;i++){
            progress.setValue(i);
                try {
                    Thread.sleep(50);
                } catch (InterruptedException ex) {
                    Logger.getLogger(WELCOME_KCCF.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        //dispose();
        if(true){
        dispose();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Library_management_system().setVisible(true);
            }
        });
        }
           
                    
            }
        });
        
        t.start();
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progress = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME KCCF");
        setMinimumSize(new java.awt.Dimension(1375, 770));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(212, 212, 212));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setPreferredSize(new java.awt.Dimension(1375, 750));
        jPanel1.setLayout(null);

        progress.setBackground(new java.awt.Color(212, 212, 212));
        progress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        progress.setForeground(new java.awt.Color(0, 153, 0));
        progress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        progress.setStringPainted(true);
        jPanel1.add(progress);
        progress.setBounds(120, 630, 1130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/runmylibrary/logokccf.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(600, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, -80, 1380, 710);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1, 0, 1375, 770);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */ 


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar progress;
    // End of variables declaration                   
}
